name: Check all Links with Lychee

on:
  workflow_dispatch:
  push:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args:
            --verbose --no-progress --retry-wait-time 10 -b https://dvc.org/
            {.github,content,src}/**/*.{css,js,jsx,md,tsx,ts,json}
          format: json
          output: out.json
