name: Check all Links with Lychee

on:
  workflow_dispatch:
  push:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Edited Files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args:
            --verbose --no-progress -b https://dvc.org/ './**/*.md'
            './**/*.html'
          format: json
          output: /tmp/output.json
