name: Merge Scheduler
on:
  pull_request:
    types: [opened, edited, synchronize]
  schedule:
    - cron: 0 6 * * *
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    if:
      ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          merge_method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
